### ISSUE TITLE
Break WINDOWS 11 (DONT USE, DANGEROUS)

### ISSUE THREAD

**Issue by Master-Antonio** [Simbiat/Anti10016#1]
This script completely broke my windows 11, the bar below is completely empty, and I can't get it back, I have to format.

Thanks so much

**Comment by Simbiat** [comment]
What the script does is, essentially, provides apps "missing" permissions, so it's most likely that it was not the script itself, that broke your installation, but one of the apps, that received the permissions.
Also, it was not tested on W11 at all. It's possible, that something was changed behind the scenes there.
